language:
  - objective-c
osx_image: xcode7.3
env:
  - DEVICE=9.2
install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install v6.2.2
  - node --version
  - npm install
  - npm install
script:
  - npm run test
after_success:
  - npm run coveralls